[package]
name = "wdk-log"
version = "0.2.0"
edition = "2021"

[dependencies]
wdk-sys = { git = "https://github.com/microsoft/windows-drivers-rs" }
log = "0.4.21"
widestring = { version = "1.1.0", default-features = false, features = [
    "alloc",
] }
